"""Idea-domain contract facade.

New idea work should import contracts from here instead of reaching into the
shared `app.models` package directly.
"""

from app.models.idea import (
    # Existing
    DraftPlan,
    ExperimentSpec,
    IdeaCandidate,
    IdeaNode,
    IdeaSession,
    IdeaSessionConfig,
    IdeaSessionStatus,
    LiteratureItem,
    RiskItem,
    StepResult,
    WorkflowTrace,
    # Dual-Graph Phase 1
    BFTSConfig,
    BFTSHandoff,
    Claim,
    ContradictionMention,
    Finding,
    FrontierSignal,
    GapEvidence,
    LiteratureCluster,
    LiteratureGraph,
    LiteratureMap,
    MethodMention,
    NoveltyEvidence,
    PaperEdge,
    PaperNode,
    QueryFamily,
    QueryPlan,
    RawPaper,
    StructuredPaper,
    # Dual-Graph Phase 2
    GraphEvidenceLink,
    KGEntity,
    KGRelation,
    PathSeedScores,
    PathSeedStep,
    ReasoningKG,
    ReasoningPathSeed,
    # Step 5 Outputs
    CandidateScores,
    GraphPatch,
    IdeaSearchEdge,
    IdeaSearchReport,
    IdeaSearchTree,
    LiteratureProbeQuery,
    LiteratureProbeResult,
    # Step 6 Outputs
    CandidateGraphEvidence,
    IdeaCritique,
    PriorWorkComparison,
    RankedIdeaOutput,
)

__all__ = [
    "DraftPlan",
    "ExperimentSpec",
    "IdeaCandidate",
    "IdeaNode",
    "IdeaSession",
    "IdeaSessionConfig",
    "IdeaSessionStatus",
    "LiteratureItem",
    "RiskItem",
    "StepResult",
    "WorkflowTrace",
    # Dual-Graph Phase 1
    "BFTSConfig",
    "BFTSHandoff",
    "Claim",
    "Finding",
    "LiteratureCluster",
    "LiteratureGraph",
    "LiteratureMap",
    "MethodMention",
    "NoveltyEvidence",
    "PaperEdge",
    "PaperNode",
    "QueryFamily",
    "QueryPlan",
    "RawPaper",
    "StructuredPaper",
    # Dual-Graph Phase 2
    "GraphEvidenceLink",
    "KGEntity",
    "KGRelation",
    "PathSeedScores",
    "PathSeedStep",
    "ReasoningKG",
    "ReasoningPathSeed",
    # Step 5 Outputs
    "CandidateScores",
    "GraphPatch",
    "IdeaSearchEdge",
    "IdeaSearchReport",
    "IdeaSearchTree",
    "LiteratureProbeQuery",
    "LiteratureProbeResult",
    # Step 6 Outputs
    "CandidateGraphEvidence",
    "IdeaCritique",
    "PriorWorkComparison",
    "RankedIdeaOutput",
]
